[[redirects]]
  from = "https://time-optimal-youtube-playlist-generator.netlify.app/api/*"
  to = "https://youtube-playlist-generator.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = “*”}